---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-replica
  labels:
    app: nginx-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-replica
  template:
    metadata:
      labels:
        app: nginx-replica
    spec:
      containers:
      - name: nginx-replica
        image: nginx:latest
        ports:
        - containerPort: 80