apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/marianu47/argo-cd.git
    path: nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
